graph TD
    A[TD Santé] --> B[TD Base de Registre]
    B --> C[Création de Modules]
    C --> D[TD PowerShell à Distance]
    D --> E[AD avec PowerShell]

    %% Styles pour rendre le diagramme plus propre
    style A fill:#f9f,stroke:#333,stroke-width:2px
    style E fill:#00ff00,stroke:#333,stroke-width:2px